// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK6KLBmQGBaiuFDbYIhNUziwfiR3DKu_E',
    appId: '1:452149900409:web:281bfacb75363696ed10a8',
    messagingSenderId: '452149900409',
    projectId: 'music-app-7f50c',
    authDomain: 'music-app-7f50c.firebaseapp.com',
    databaseURL: 'https://music-app-7f50c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-app-7f50c.appspot.com',
    measurementId: 'G-EHF23M91R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlI8SZOFB15w-s5Hobecd596wE6iz4TFo',
    appId: '1:452149900409:android:33cf8b16903bd416ed10a8',
    messagingSenderId: '452149900409',
    projectId: 'music-app-7f50c',
    databaseURL: 'https://music-app-7f50c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-app-7f50c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmwOKPRQk9WiCQ6-mco9-aRWHzPv_YemQ',
    appId: '1:452149900409:ios:ba7e2637e088a043ed10a8',
    messagingSenderId: '452149900409',
    projectId: 'music-app-7f50c',
    databaseURL: 'https://music-app-7f50c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-app-7f50c.appspot.com',
    androidClientId: '452149900409-llu87t23thd1d7jnonojer78smdcddre.apps.googleusercontent.com',
    iosClientId: '452149900409-3oplc53tu2i4hjjgr422ki1keha7cekr.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmwOKPRQk9WiCQ6-mco9-aRWHzPv_YemQ',
    appId: '1:452149900409:ios:ba7e2637e088a043ed10a8',
    messagingSenderId: '452149900409',
    projectId: 'music-app-7f50c',
    databaseURL: 'https://music-app-7f50c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-app-7f50c.appspot.com',
    androidClientId: '452149900409-llu87t23thd1d7jnonojer78smdcddre.apps.googleusercontent.com',
    iosClientId: '452149900409-3oplc53tu2i4hjjgr422ki1keha7cekr.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK6KLBmQGBaiuFDbYIhNUziwfiR3DKu_E',
    appId: '1:452149900409:web:e1ca2e97f372d4d9ed10a8',
    messagingSenderId: '452149900409',
    projectId: 'music-app-7f50c',
    authDomain: 'music-app-7f50c.firebaseapp.com',
    databaseURL: 'https://music-app-7f50c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'music-app-7f50c.appspot.com',
    measurementId: 'G-V648MT9J0G',
  );

}